### ISSUE TITLE
Error Via Composer

### ISSUE THREAD

**Issue by mmendesico** [PicPay/magento2#16]
Olá a comunidade.. 
Tive um problema no composer para a minha aplicação do magento dando o seguinte erro:
" Could not find a version of package picpay/magento2 matching your minimum-s
  tability (stable). Require it with an explicit version constraint allowing
  its desired stability. "
Poderiam me auxiliar em uma solução?

**Comment by gabrielhaase** [comment]
Mesmo problema por aqui!!

**Comment by mmendesico** [comment]
Se tiver alguma instrução para instalação manual, agradeço se informarem.

**Comment by lucasqm** [comment]
Problema corrigido no PR #17
