### ISSUE TITLE
API do PicPay para .NET

### ISSUE THREAD

**Issue by marcelowu** [PicPay/magento2#6]
vcs vai lançar a versao do nopcommerce?

https://github.com/matmiranda/PicPay-NET

O jeito mais simples e rápido de integrar o PicPay a sua aplicação .NET e feito com base nas APIs REST do PicPay.

https://github.com/nopSolutions/nopCommerce

**Comment by jgcl** [comment]
Olá Marcelo, tudo certo?

Por enquanto ainda não está em nosso backlog o nopcommerce.

Obrigado pelo interesse.
